<?php

namespace AppBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{

    public function searchByTitle($keyword)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT i FROM AppBundle:Image i WHERE i.title Like :keyword"
            )
            ->setParameter('keyword','%'.$keyword.'%')
            ->getResult();
    }

    public function sortByTitle()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i FROM AppBundle:Image i ORDER BY i.title ASC'
            )
            ->getResult();
    }

    public function sortByCreationDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i FROM AppBundle:Image i ORDER BY i.dateOfCreation ASC'
            )
            ->getResult();
    }

    public function sortByAllowedDays()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i FROM AppBundle:Image i ORDER BY i.allowedDays ASC'
            )
            ->getResult();
    }

}
